trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: Maven@4
#   inputs:
#     mavenPomFile: 'pom.xml'
#     goals: 'clean package'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.17'
#     mavenVersionOption: 'Default'
#     mavenAuthenticateFeed: true
#     effectivePomSkip: false
#     sonarQubeRunAnalysis: false
- script: |
    # wget  https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.15.0/codeql-bundle-linux64.tar.gz
    ls
    tar -xvzf codeql-bundle-linux64.tar.gz
    ls
    pwd
    
    # chmod +x codeql-runner-linux 
  displayName: 'Get latest CodeQL package. Install on Agent.'
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'maven'

- script: |
    mv $(codeql_path)/codeql /home/vsts/work/1/codeql
    chmod +x /home/vsts/work/1/codeql
    pwd
    ./codeql database create java-database --language=java --command='mvn clean package' 
    mv $(codeql_path)/qlpacks/codeql/java-queries/0.8.0/codeql-suites/java-code-scanning.qls $(codeql_path)
    ./codeql database analyze java-database java-code-scanning.qls --format=sarifv2.1.0 --sarif-category=java --output=/home/vsts/work/1/s/codeql/java-database.sarif
    ./codeql database finalize java-database 
    cd /home/vsts/work/1/s/codeql
    ls
    # ./codeql github upload-results  --repository=jananiorganiza/test3 --ref=refs/heads/main --commit=67453583387e8ee574963cd3e0a16d7a5bee2f5a --sarif=/home/vsts/work/1/s/codeql/temp/java-database.sarif --github-url=https://github.com --github-auth-stdin=$(GITHUB_PAT)
    # ./codeql database init
  displayName: codeql analyze
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#      ./codeql-runner-linux init \
#      --repository jananiorganiza/test \
#      --github-url https://github.com \
#      --github-auth $(GITHUB_PAT) \
#      --languages java \
#      --spawn_strategy=local \
#      --config-file .github/codeql/codeql-config.yml
  
# - script: |
#     ./codeql-runner-linux analyze \
#     --repository jananiorganiza/test  \
#     --github-url https://github.com \
#     --github-auth $(GITHUB_PAT) \
#     --commit $(Build.SourceVersion) \
#     --ref $(Build.SourceBranch)
#   displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       echo $(Build.SourcesDirectory)
#       cd $(Build.SourcesDirectory)
#       ls